"""empty message

Revision ID: 1c6150b1f722
Revises: 3fbcfb78de48
Create Date: 2021-08-26 19:32:53.358889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6150b1f722'
down_revision = '3fbcfb78de48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaClasses', sa.Column('classDate', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yogaClasses', 'classDate')
    # ### end Alembic commands ###
