"""empty message

Revision ID: 3fbcfb78de48
Revises: 55b32acc0506
Create Date: 2021-08-26 17:21:17.101365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbcfb78de48'
down_revision = '55b32acc0506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaClasses', sa.Column('pic', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yogaClasses', 'pic')
    # ### end Alembic commands ###
