"""empty message

Revision ID: 923dc2ac2704
Revises: a93604cf7fe0
Create Date: 2021-09-03 17:31:20.783360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923dc2ac2704'
down_revision = 'a93604cf7fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isTeacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isTeacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
